# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 099b1ce9c65378d72751accbec2e9e5f6edd7a2438f6bf760f98f40ebd256d15a27181a3b222bdb0957bd868c2166eab97b05b3ac3b32ec75d1477c8babf83bf

test:
  secret_key_base: 5644d40c5c33a91552cdaa8969c82c6d988ec04e449bef0d9e16f7f55c6273f291cb16fc20246d68d802741e5465588aacdc6b6c8f17077d5086e51734cc61e7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
